### PR TITLE
Extract comparison - 2.48.2.76781

### PR DESCRIPTION
**Pull request by MGatner**
My extraction differs significantly. I would like to get set up to have identical output so I could contribute. Could you please review this diff and see if you could determine what I did wrong?

Deets:

OS: macOS
Version: 4.3.1
Patch: 2.48.2.76781
Environment: Live
Commands:
```
heroesdata --extract-data all --extract-images all --localization all --localized-text --warnings
heroesdata localized-json ./gamestrings-76781
```

### CODE REVIEW

**Comment by koliva8245** [comment]
Yeah... apparently it's because the default sort comparer for string performs differently between Windows and macOS/Linux.  The macOS/Linux sorting is the one I want though.

**Comment by MGatner** [comment]
So... Is my version how you want it?

Did you look at the data files as well? They have significant value differences, beyond just ordering.

**Comment by koliva8245** [comment]
Yeah, yours is good.  Is there any value difference? It's hard to tell for the veterancy behavior because of the sorting difference.

**Comment by MGatner** [comment]
Ohhh yeah I think you're right. Some of them were so spread it looked like value changes but I think it is just sorting.

**Comment by MGatner** [comment]
If that's the case you are welcome to merge this, and I'm all set for just-about-automated repo updates on patch days.

**Comment by koliva8245** [comment]
I made a fix to the hdp develop branch. Can you download the latest dev and re-extract. It heavily re-sorts the gamestrings but it should make it consistent between operating systems.

**Comment by MGatner** [comment]
I’ll give it a shot and update the PR. Might be tonight before I’m available.

**Comment by MGatner** [comment]
Rerun with 20191019.1 - things definitely moved around but still don't seem to be in the same order as the repo currently has.

**Comment by koliva8245** [comment]
Yes, like I said it will heavily re-sort the order. I want you to submit a commit of yours, so I can compare it to mine. 
I committed the new gamestrings for 76781, so update your branch and compare.

**Pull request closed without merging**
