### PR TITLE
Take 2 with 20191019.1

### PR DESCRIPTION
**Pull request by MGatner**
Continuation of #1. Looks like the gamestrings are all identical now, but still some order differences in the data files.

### CODE REVIEW

**Comment by koliva8245** [comment]
Right, I didn't fix the data sorting. Get latest and try again.

**Comment by MGatner** [comment]
Looks like it is still running, but I'll give it a shot when it's done.

**Comment by MGatner** [comment]
That did it! Completely identical, 0 diff. Nice work.

I will plan to send over PRs on patch day whenever I get to it and you haven't posted yet. If you every want me to change anything just let me know.

**Comment by koliva8245** [comment]
Great. Also when you submit a pull request, you need to include the .hdp.json file.

**Comment by MGatner** [comment]
Will do! I assume I draft that myself, it's not generated anywhere?

**Comment by koliva8245** [comment]
Right, you have to create it yourself.  You can get the version from hdp using --version and parse out the version number.

**Pull request closed without merging**
