### PR TITLE
Add Composer definition

### PR DESCRIPTION
**Pull request by MGatner**
Adds **composer.json** to allow PHP projects to define version dependencies from this repo.

### CODE REVIEW

**Comment by koliva8245** [comment]
I really don't want to add this. This repo shouldn't exactly be used as a project dependency.

**Comment by MGatner** [comment]
Well I'm already using it as a dependency, but I have to update my fork with the `composer.json` file every time before it picks up the newest versions so I thought I would see about adding it here.

Given all the repos downstream from this, what is your reluctance to using it? The projects I use it for (and a new one I'm starting on) are towards the end of automating the hero data distribution. This repo is awesome and incredibly thorough, but most of the "consumers" want a simpler format to parse.

**Comment by koliva8245** [comment]
Composer is for php, this repo is to be agnostic to all languages.

**Comment by MGatner** [comment]
Sure but it isn't unusual for language-agnostic repos to host definitions. Think of it as "I want to publish my content to _____". In this case it is to Packagist (or faux-Packagist since you don't actually have to submit it). It might make sense to include package.json as well so Node users could import it. 

Ultimately it's up to you but I need it so the alternative is tools using my fork with the file.

**Comment by koliva8245** [comment]
Like I said before this shouldn't be used a dependency. This repo is merely just hosting files. Not to mention that this repo is going to keep increasing in size.

**Pull request closed without merging**
