### PR TITLE
Add Deathwing PTR patch

### PR DESCRIPTION
**Pull request by MGatner**

### CODE REVIEW

**Comment by koliva8245** [comment]
Wrong file name formatting, you're missing the version number.

**Comment by MGatner** [comment]
This is straight from HDP. Bug maybe?

**Comment by MGatner** [comment]
Maybe related to https://github.com/HeroesToolChest/HeroesDataParser/issues/67#issuecomment-558867889 ?

**Comment by koliva8245** [comment]
Did you run HDP against the Heroes of the Storm directory or against an already extract game files?

**Comment by MGatner** [comment]
I ran it against the PTR directory, same commands I always do except with the different directory.

**Comment by koliva8245** [comment]
Rename the files manually.

**Comment by koliva8245** [comment]
Or you can just use the latest hdp build that fixes the problem.

**Comment by MGatner** [comment]
👍

**Pull request merged**
